name: Print Tag

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      new_core_tag: 
        description: 'New variable for the action'
        required: false

jobs:
  print_tag:
    runs-on: ubuntu-latest
    steps:
  
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set Environment Variable ENV
      run: |
        python3 CreateTag.py ${{ secrets.GAT_TAG }}
        
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker build
      run: |
        docker build --build-arg ALPINE_VERSION=$LAST_CORE_TAG -t my_image . --load
