name: Print Tag

on:
  workflow_dispatch:
    inputs:
      new_variable: 
        description: 'New variable for the action'
        required: true

jobs:
  print_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Print Tag
      run: |
        echo "New variable: ${{ github.event.inputs.new_variable }}"
