name: Print Tag

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      new_core_tag:
        description: 'New variable for the action'
        required: false

env:
  CORE_TAG: ${{ github.event.inputs.new_core_tag }}
  TAG_MANIFEST: latest

jobs:
  print_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Environment Variable ENV
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "VERSION=latest-tag" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "VERSION=latest" >> $GITHUB_ENV
          fi        


      - name: Print All Useful data
        run: |
          echo "ENV: ${{ env.ENV }}"
          echo "VERSION: ${{ env.VERSION }}"
          echo "TAG_MANIFEST: ${{ env.TAG_MANIFEST }}"