name: Print Tag

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      new_core_tag: 
        description: 'New variable for the action'
        required: false

jobs:
  print_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Environment Variable ENV
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "CORE_TAG=$(python3 GetTag.py ${{ secrets.GET_TAG }})" >> $GITHUB_ENV   
          elif [ "${{ github.ref }}" == "refs/heads/dev" ] || [ "${{ env.CORE_TAG }}" == "latest" ]; then
        # for case when code push to dev (CORE_TAG=None)  CORE_TAG needed to init
            echo "CORE_TAG=latest" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Print GET_TAG as last tag core
        run: |
          echo "Name from GET_TAG: $GET_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build
        run: |
          docker build --build-arg ALPINE_VERSION=$LAST_CORE_TAG -t my_image . --load
